### ISSUE TITLE
Arcs / curves

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#11]
Should we support arcs? Does LFF support them?

If yes, what types of arcs? Only circular arcs?

Should we recommend or require that implementations provide a way to flatten arcs, returning them as polylines?

Would Bézier curves (quadratic / cubic) be totally out of scope? Efficient flattening is not *that* hard. [Here](https://github.com/nical/lyon/blob/master/bezier/src/flatten_cubic.rs) is the implementation by [Lyon](https://docs.rs/lyon_bezier/0.8.0/lyon_bezier/) for example, based on [this](http://cis.usouthal.edu/~hain/general/Publications/Bezier/Bezier%20Offset%20Curves.pdf) paper. (Ignore the Math, the implementation should be easier to follow.)

**Comment by ubruhin** [comment]
> Should we support arcs?

Yes - fonts without arcs look very ugly ;)

> Does LFF support them?

Yes. See also:
- http://forum.librecad.org/Where-I-can-find-LFF-specification-arcs-td5158044.html
- https://github.com/Rallaz/LibreCAD/wiki/lff-definition

> If yes, what types of arcs? Only circular arcs?

Yes, I would say only circular.

> Should we recommend or require that implementations provide a way to flatten arcs, returning them as polylines?

That would be great (recommendation should be enough).

> Would Bézier curves (quadratic / cubic) be totally out of scope?

Not sure ;) But probably arcs are really enough to get nice looking fonts, so no Bézier curves are required anyway(?). Maybe we can still add support for Bézier curves some time, but then it would be much more important to provide flattening methods I think (for example LibrePCB would require them).

**Comment by dbrgn** [comment]
I don't really understand the definitions used by LFF. @ubruhin can you come up with a specification (and maybe 1, 2 examples) of arcs?

**Comment by ubruhin** [comment]
> I don't really understand the definitions used by LFF.

Basically the arcs are defined nearly the same way as LibrePCB :smiley:
![polygon_arcs](https://raw.githubusercontent.com/LibrePCB/LibrePCB/master/dev/graphics/png/polygon_arcs.png)

The only difference is that in LFF the angle of the arc is not specified in degrees, but in radians, calculated by `tan(angle_rad / 4)`. But I have no idea why ;)

To convert the bulge value from LFF files to degrees, `rad2deg(atan(bulge)) * 4` can be used.

> can you come up with a specification (and maybe 1, 2 examples) of arcs?

I can try it ;) But it would still be interesting to know why LFF does not specify the angle in degrees, which would be more intuitive and easier IMO...

**Comment by ubruhin** [comment]
I have created two different specifications for circular arc segments:

1. Angle given as tangens (like in LFF): #18 
2. Angle given in degrees: #19 

Now we have to decide which variant is the better one ;)

## Background

The goal is to have a specification of circular arcs which is easy to understand, simple to implement, space saving (short numbers in the file) and also numerically stable (graphical deviation between different implementations should be minimal, for example an implementation with single precision float compared to double precision float).

Regarding the numerical stability: I think we need to keep deviations of the [sagitta](https://en.wikipedia.org/wiki/Sagitta_(geometry)) as small as possible. The sagitta is called *h* in following diagram (from [Wikipedia](https://de.wikipedia.org/wiki/Segment_(Kreis))):
[![sagitta](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Circular_segment.svg/320px-Circular_segment.svg.png)](https://de.wikipedia.org/wiki/Segment_(Kreis))

So the number which defines the arc segment in a FontoBene file should be linear to the sagitta to have the same resolution over the whole range from 0° to ~360° arc segments. But it should be independent from the start and end point (i.e. size) of the arc segment.

This is exactly what LFF and DXF do: In their file format, an arc segment is specified by `tan(x/4)`, where `x` is the included angle of the arc segment. This so-called *bulge* provides the same accuracy from 0° to ~360° arcs, which is probably the reason why they have chosen this definition. It's just the most reasonable definition from the mathematical point of view.

But there are still some disadvantages:
- For arcs with a large angle (near 360°), the bulge number goes to infinity (caused by the tangens function). This could still lead to issues between different implementations, e.g. single precision float compared to double precision float because they have different range and resolution.
- The bulge numbers in files are not very readable. They need many decimals to specify even very common angles and the reader needs a calculator to get the angle in degrees. Example: `0.414213562` specifies a 90° angle.

A possible solution would be to specify the angle in degrees (to improve readability) while only allowing angles in the range -180...+180° (to minimize numerical instability). Arcs with more than 180° needs then be split up into two smaller arcs.

In the range of -180...+180° the `tan(x/4)` is not very different from a linear function:
![fontobene_plot](https://user-images.githubusercontent.com/5374821/34358816-2e67733e-ea53-11e7-813b-1d4444295c83.png)

So, specifying the angle in degrees (with the 180° limit) may be a good compromise.

What do you think @dbrgn @rnestler?

**Comment by dbrgn** [comment]
Yep, I like the approach with the angle in the range -9 to 9 :)
