### ISSUE TITLE
Monospace support

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#14]
Things to be added:

- [ ] Monospace?

**Comment by ubruhin** [comment]
LFF also specifies following parameters in each font file for the font layout engine:
- LetterSpacing: Horizontal space between each character. Default is 1/3 of the font height.
- WordSpacing: Width of the space character. Default is 3/4 of the font height.
- LineSpacingFactor: A multiplier for the line spacing, in addition to the hardcoded (in source code) value of 5/3 of the font height. Default is 1, so the default line spacing results to 1.666 times the font height.

I think it would make sense to add all these parameters also to fontobene files, because they are *very* useful for the layout engine. But instead of having a hardcoded line spacing factor, I would also specify the full line spacing factor (e.g. 1.666) directly in the font files, because IMHO this is simpler, more intuitive, and removes the need for a hardcoded "magic number".

What do you think @dbrgn?

Regarding monospace fonts: I think this would be a pretty important feature, but I'm not yet sure how it should be implemented exactly.
- Can a fontobene font be used as a monospace font and a proportional font at the same time, so it's just up to the layout engine to switch monospace on/off? Or is every font either a monospace font or a proportional font, but not both?
- Do we need to add a property "MonospaceWidth" to the font files to specify the character width used by the layout engine?
- Should glyphs of monospace fonts be placed at coordinate (0,0) as usual (like the character "I" which is on x-coordinate 0), or should the glyphs be centered (e.g. x-coordinate 4.5 if the monospaced glyph width is 9)?

**Comment by dbrgn** [comment]
@ubruhin that discussion probably belongs in #5. I also left some comments in #29.

**Comment by dbrgn** [comment]
Now that we have whitespace support, someone could make a monospace font by hand, but it would be very tedious.

My suggestion would be:

- Add an optional `monospace_width` property to the font metadata. If set, the value specifies the width of a glyph (excluding global spacing).
- Glyphs MUST be centered in that "container". Whitespace SHALL also be considered when calculating the actual width of the glyph. Whitespace MAY be used to offset the x-position inside the container.
- Glyphs SHOULD not be wider than the `monospace_width`. Glyphs that are wider than the `monospace_width` SHOULD also be centered. When a parser encounters such glyphs, that SHOULD result in a warning message being reported to the user.

In theory, a parser without monospace support could just treat such a font as a regular non-monospace font, but it would probably look ugly.

@ubruhin @rnestler RFC

**Comment by ubruhin** [comment]
> Glyphs MUST be centered in that "container".

How do you mean that, should the *glyph polylines itself* contain an x-offset, or are glyphs left-aligned to x=0 (as currently defined in the specs) and only *the layout engine* centers the glyphs afterwards?

**Comment by dbrgn** [comment]
The layout engine should center the glyph. Good point, that's an important distinction :)

**Comment by ubruhin** [comment]
Sounds good :+1: A PR to update the specs would be nice :)

Maybe I'll quickly try this out in librepcb to see if it works as expected.

**Comment by ubruhin** [comment]
> Maybe I'll quickly try this out in librepcb to see if it works as expected.

Seems to work (and as expected, it doesn't look nice with non-monospace fonts):
![auswahl_010](https://user-images.githubusercontent.com/5374821/38783456-8a199ee0-4102-11e8-9450-cf9585d25a03.png)

@dbrgn Would you open a PR to add it to the specifications?

**Comment by dbrgn** [comment]
Will do!
