### ISSUE TITLE
Scope of specification

### ISSUE THREAD

**Issue by ubruhin** [fontobene/fontobene#6]
What's actually the scope of the fontobene specification?

- Only the file format itself (leave rendering implementation specific)?
- The file format + the exact mechanism how the text should be rendered (including letter/word/line spacing, aligning, scaling, kerning, ...)?

I think the latter one would be better because it makes the parser interchangeable. So an application could switch from one parser to another and will get the exact same result. But of course then we need to specify every tiny detail of the geometry ;)

**Comment by dbrgn** [comment]
I'd strongly vote in favor of number 1 (only the file format). We aren't experts in geometry / font layout, so that should be done separately. If we specify every detail, we make optimization by implementations impossible without breaking conformity with the spec.

It would also make parsers much more complex. Some implementations might not actually need anything complex / nicely layouted.

**Comment by ubruhin** [comment]
I agree. But maybe we could still add a *very* simple definition how rendering should be done exactly, and parsers could decide whether they want to implement this kind of rendering or not. Then all parsers which implement this "standard conform rendering algorithm" are able to generate the exact same polylines for a given text, and are thus interchangeable.

**Comment by dbrgn** [comment]
We ended up choosing a middle ground between the two approaches (see #29, #32, #35, #36).
