### ISSUE TITLE
Meta-Glyphs

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#9]
Should we add a possibility to define meta-glyphs that are only used for references / expansion, but are not valid glyphs themselves? This could be used to "extract" frequently used shapes. (Could be interesting especially in combination with #8.)

**Comment by ubruhin** [comment]
Sounds interesting, but I'm not sure if this would be useful in practice because probably most font files will be generated automatically (e.g. using tools like `lff2fontobene` or `ttf2fontobene`) which may not be able to generate (reasonable) meta glyphs...

In addition, for some "meta glyphs" it seems there are already code points defined, for example the [COMBINING DIAERESIS](https://codepoints.net/U+0308). But how does unicode handle different heights of characters when combining the COMBINING DIAERESIS with an arbitrary character? e.g. the diaeresis of "ä" are not at the same position as of "Ä".

**Comment by dbrgn** [comment]
> But how does unicode handle different heights of characters

Unicode doesn't do anything about it, it just specifies what the COMBINING DIAERESIS means. Rendering is totally up to the font systems :)

I actually thought about that issue too. We *could* add metadata to references:

```
[0041] A
@0308 dx=3 dy=-5
...
```

...but then the font parser actually needs to deal with coordinate transformations, something that right now it doesn't (it just "copy-pastes" reference targets into the glyph). Also, from a readability and simplicity perspective, in cases like these it would probably be better to just include the correctly translated polylines into the target glyph without any references.

**Comment by dbrgn** [comment]
I think we should probably not do this. It would be an interesting optimization, but it would make the font format more complex.

Opinons, @rnestler @ubruhin?

**Comment by ubruhin** [comment]
> I think we should probably not do this.

Agree!

**Comment by dbrgn** [comment]
Alright :)

**Comment by dbrgn** [comment]
As a sidenote, my main use case was for uses like the [diaresis](https://en.wikipedia.org/wiki/Diaeresis_%28diacritic%29) to form the various umlauts, but there is already a unicode codepoint for that. The same thing counts for other diacritics like the forward and backward accent.
